config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :models
  
  resources :exams
  resources :questions
  post '/exams/submit' => 'exams#submit_exam', as: :exam_submit
  get '/show_results' => 'exams#show_result', as: :show_result
  root 'exams#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
    has_many :questions
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/question.rb
class Question < ActiveRecord::Base
    belongs_to :exam
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_login.rb
class UserLogin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  #before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @exam = Exam.find(params[:id])
    @questions = @exam.questions
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new()
    @exam.name = params[:name]
    @exam.name = params[:description]
    @exam.save!
    flash[:notice] = "#{@exam.name} was successfully created."
    redirect_to(exams_path)
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  # def update
  #     #respond_to do |format|
  #   @exam.update(exam_params) #if
  #   # flash[:notice] = "#{@exam.name} was successfully created."
  #   redirect_to(exams_path)
  #     #   format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
  #     #   format.json { render :show, status: :ok, location: @exam }
  #     # else
  #     #   format.html { render :edit }
  #     #   format.json { render json: @exam.errors, status: :unprocessable_entity }
  #     # end
  #   # end
  # end

  # DELETE /exams/1
  # DELETE /exams/1.json
 
  # def destroy
  #   @exam = Exam.find(params[:id])
  #   @exam.destroy
  #   flash[:notice] = "Exam '#{@exam.name}' deleted."
  #   redirect_to exam_path
  # end
  
  def submit_exam
    @exam = Exam.find(params[:exam_id])
    all_questions = @exam.questions.to_a.as_json
    @score = 0
    all_questions.each do |q_hash|
      q_id = q_hash['id']
      @score += params[q_id.to_s] == q_hash['answer'] ? 1 : 0 
      puts "asdasdadaaaasssssssssssssssssssssssssssssssssssssssssss"
      puts params[q_id]
      puts params[q_id]
    end
    redirect_to show_result_path(score: @score, exam_name: @exam.name)
  end
  
  def show_result
    @score = params[:score]
    @exam_name = params[:exam_name]
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_exam
    #  @exam = Exam.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def exam_params
    #   params.require(:exam).permit(:name,:description)
    # end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    
    def new
        @exams = Exam.all
    end
    
    def create
        question = Question.new()
        question.content = params[:content]
        options_string = ''
        (1..4).each do |opt_no|
            options_string += "#{params["option#{opt_no}"]}\r\n"    
        end
        question.options = options_string
        question.exam_id = params[:exam_id]
        question.answer = params[:answer]
        question.save
        redirect_to new_question_path
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/exams/index.html.haml
.row
  %div{:class => 'intro'}
    %h1 Welcome to Online Examination Portal!
%hr/
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th.col-md-8 List of Exams
      %th.col-md-2
  %tbody
    - @exams.each do |exam|
      %tr
        %td= link_to exam.name, exam_path(exam.id),:class => "exam"
        %td= link_to "Edit", edit_exam_path(exam.id),:class => "edit-delete"
        %td= link_to("Delete", exam_path(exam),  :method => :delete,:class => "edit-delete")
%p= link_to "Create Exam", new_exam_path
%p= link_to "Create New Question ", new_question_path
%br/

app/views/exams/new.html.haml
.row
  %div{:class => 'intro'}
    %h1 Create New Exam
  %div
    =form_tag exams_path, method: :post  do 
      =text_field_tag :name,'',placeholder: 'Enter Exam Name'
      =text_field_tag :description,'',placeholder: 'Enter Exam Description'
      =submit_tag 'Create Exam'
%hr/
%br/

app/views/exams/show.html.haml
.row
  %div{:class => 'intro'}
    %h1= @exam.name
    %h2= @exam.description
  %div
    =form_tag exam_submit_path,method: :post do 
      =hidden_field_tag :exam_id,@exam.id
      -@questions.each do |q|
        %h3=q.content
        %br
        -q.options.split("\r\n").compact.each do |o|
          =radio_button_tag q.id, o
          =label_tag "#{q.id}_#{o}", o
          %br
      =submit_tag 'Submit Quiz'  
%hr/
%br/

app/views/exams/show_result.html.haml
%div
    %h3="You Have Scored #{@score} in #{@exam_name}"

app/views/layouts/_footer.html.haml
%footer{:class => "index-footer"}
  .container
    .row{:class => "index-footer-row"}
      .col-md-6
      .col-md-3

app/views/layouts/_navbar.html.haml
%nav{:class => "index-nav"}
  .container
    %navbar-brand
    %h{:class => "nav-header"} Exams-for-Geeks
    
    = link_to "Sign Up",  new_model_registration_path, :class=> "sign"
    = link_to "Sign In", new_model_session_path, :class=> "sign"
    
#myModal.modal.fade.bs-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md
    .modal-content
      %br
        .modal-body
          #myTabContent.tab-content
        .modal-footer

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Exam2
    = stylesheet_link_tag  "application"
    = javascript_include_tag "application"

    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container{:class=> "body-container"}
      - if alert
        %p.alert= alert
      = yield
    = render 'layouts/footer'

app/views/questions/new.html.haml
.row
  %div{:class => 'intro'}
    %h1 Create New Question
  %div
    =form_tag questions_path, method: :post  do 
      =text_field_tag :content,'',placeholder: 'Enter Question'
      =text_field_tag :option1,'',placeholder: 'Option 1'
      =text_field_tag :option2,'',placeholder: 'Option 2'
      =text_field_tag :option3,'',placeholder: 'Option 3'
      =text_field_tag :option4,'',placeholder: 'Option 4'
      =text_field_tag :answer,'',placeholder: 'Answer'
      =select_tag :exam_id, options_from_collection_for_select(@exams, 'id', 'name'),prompt: 'Select Exam Name'
      =submit_tag 'Add Question To Exam'
%hr/
%br/